### ISSUE TITLE
guce.oath.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishCookieConsent#17]
`https://guce.oath.com/collectConsent?sessionId=3_cc-session_7828101c-e57e-42e8-ba67-c8553811e932&lang=&inline=false&jsVersion=null&experiment=null`

### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 64
### Dodatkowe informacje mogące mieć znaczenie
pętla przekierowań i na końcu błąd:

> Oops, something went wrong
> Please try again later

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Teraz zrobili `/v2/` i nie wykrywa domeny.

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem w czym problem, twoja reguła działa, możesz dodać...

**Comment by krystian3w** [comment]
Miałem wątpliwości co do jakości regex i tego, że część użytkowników nie zobaczy wcale tej ściany ciastek.

I chyba już kompletnie wygasili `guce.oath.com` jak ich MS mocniej wchłonął.
