### ISSUE TITLE
Jakieś puste shadow rooty

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#18]
![image](https://user-images.githubusercontent.com/35370833/50965910-acb97100-14d3-11e9-8f2c-ed6b35bd04d7.png) |
--- |

`https://sportowefakty.wp.pl/pilka-nozna/776220/dlaczego-przegralismy-mundial-stworzylismy-dla-was-raport-alternatywny`

**Comment by hawkeye116477** [comment]
To było do tych filmików Twitterowych. Jak elementu nie ma, to dlatego wywala ten błąd, nie wiem czy coś da się z tym zrobić. Może @kejn ma pomysł?

**Comment by kejn** [comment]
Idąc za dokumentacją `querySelector()` zwraca pierwszy znaleziony element albo `null` jeśli niczego nie znalazł.

Wygląda więc na to, że nie zawsze znajduje ten element, tak jak sugerował @hawkeye116477, więc w zasadzie wystarczyłoby sprawdzać czy cokolwiek znalazł. Przerobiłbym to tak:
```
function removeFromShadow(shadowHostArg, element, urlArg)
{
    if(getUrlCondition(urlArg))
    {
        var readyStateCheckInterval = setInterval(function() {
            if (document.readyState === "complete") {
                var shadowHost = document.querySelectorAll(shadowHostArg);
                var cookieConsentShadow = document.querySelector(shadowHostArg);
                if (cookieConsentShadow) {
                    var cookieConsent = cookieConsentShadow.shadowRoot.querySelector(element);
                    if (cookieConsent)
                    {
                        for (var i=0; i<shadowHost.length; ++i)
                        {
                            shadowHost[i].shadowRoot.querySelector(element).remove();
                        }
                    }
                }
            }
        }, 1000);
    }
}
```

**Comment by kejn** [comment]
Ewentualnie jak to zadziała, to można by jeszcze zrobić małą zmianę i brać `cookieConsentShadow` ze zmiennej `shadowHost` (pierwszy element), bo to jest ten sam selektor.

**Comment by kejn** [comment]
Potwierdzone, już się nie sypie. Podalibyście jeszcze jakiś przykładowy link, żeby sprawdzić czy działa z tymi filmikami?

**Comment by KNsltq** [comment]
nic się nie sypie, więc powinno być ok 👍

**Comment by hawkeye116477** [comment]
Potwierdzam, jest ok. Dzięki za pomoc.

**Comment by krystian3w** [comment]
```
https://fakty.interia.pl/pomorskie/news-gdansk-trwaja-poszukiwania-nastolatka-ktory-kapal-sie-w-morz,nId,3068125
```

Na shadow rooty nie zgodziła się Opera i Mozilla?

**Comment by hawkeye116477** [comment]
@krystian3w Nic nie powiedzieli w tej sprawie, po prostu ja uznałem, że nie pasują tutaj, bo miała być akceptacja a nie zabawa w chowanego :smile:

**Comment by krystian3w** [comment]
Ja tam sobie znów włączyłem po prostu blokadę ciastek z stron obcych / nieodwiedzonych.
