### ISSUE TITLE
YouTube.com | Google.*

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#2]
#  `Google.pl` / `Google.com` / `YouTube.com`

* ~~Stopowane filmy YouTube. Niby progres obejrzenia 1-10 sekund psuje teraz samo Google, podobnie z parametrem `&t=`.~~ - Google rezygnuje z pop-upa i wdrożył cookie-wall, jak klikanie nie działa to trzeba użyć https://github.com/JustOff/scriptlet-doctor#readme lub `security.csp.enable` wyłączyć (stan `false).

* Ściany ciastek trudne do forsowania skryptletami/html filteringiem (częściowo działa blokada obsługi ciastek pod subdomenę).

---

<details> <summary> dawne... </summary><br>

---

<details> <summary> stare - naprawione</summary><br>

- ~~`www.rexona.com/pl/technologie/invisible-black-and-white.html`~~
- ~~`www.rexona.com/pl/home.html`~~
- ~~`unileverfoodsolutions.pl`~~
- ~~`fandom.com`~~
- ~~`wylecz.to` / `drogerium.pl `~~

</details>

---

<details> <summary> stare rexony - błędy EasyList </summary><br>

Blokują sobie część grafik do akceptacji cookies.

![image](https://user-images.githubusercontent.com/35370833/48479098-8f836180-e806-11e8-9222-3a3f45da6a7a.png) | ![image](https://user-images.githubusercontent.com/35370833/48479125-a75ae580-e806-11e8-914e-2a46a24fc936.png)
--- | ---

</details></details>

**Comment by hawkeye116477** [comment]
@krystian3w To EasyList blokuje te grafiki.

**Comment by hawkeye116477** [comment]
@krystian3w Niemożliwe, u mnie nic nie odblokowuje, jedynie po dodaniu wyjątku jest ok, nie trzeba nic klikać.

**Comment by krystian3w** [comment]
Ja klikam w komunikat, to Opera je normalnie ładuje - może mają inne adresy, aż tak nie sprawdzałem.

Przy okazji zerknij na `www.unileverfoodsolutions.pl`, może grafiki z prawej da się odblokować bez akceptacji Evidon?

**Comment by krystian3w** [comment]
Dasz radę dorzucić `fandom.com` do wiki?

`https://gta.fandom.com/pl/wiki/Grand_Theft_Auto_Wiki`

**Comment by hawkeye116477** [comment]
@krystian3w Oczywiście, patrz i ucz się :smile:.

**Comment by krystian3w** [comment]
`wylecz.to` / `drogerium.pl` może akceptacja cookie w dodatku?

Chyba że za to też dadzą pozew na miliony monet :moneybag:.

**Comment by MajkiIT** [comment]
@krystian3w hahahaha

**Comment by hawkeye116477** [comment]
Jak będziemy akceptować, to raczej powinni się cieszyć :smile:.

**Comment by krystian3w** [comment]
`sourceforge.net` chyba że wybór w ich cookies jest problematyczny jak u jspenguin i zbyt zagranicznie i może zbyt już mało popularne.

**Comment by hawkeye116477** [comment]
@krystian3w Nie ma problemu, będziemy wszystko akceptować :smile:

**Comment by krystian3w** [comment]
Bez przesady może tylko popularne, nie miało to być drugie lepsze `I do not care about cookies`.

**Comment by hawkeye116477** [comment]
@krystian3w Miałem na myśli, że wszystkie opcje w pop-upie. Chociaż tak z drugiej strony to nie wiem czy się opłaci to dodawać, raczej takie popularne to chyba teraz już nie jest.

**Comment by krystian3w** [comment]
`Google.pl` i ich privacy wall na grafikach?

Zbyt losowe?

**Comment by hawkeye116477** [comment]
@krystian3w A kiedy i gdzie konkretnie to się pojawia? Bo generalnie to niby coś tam już jest na liście Rodo-Ciasteczkowej.

**Comment by krystian3w** [comment]
Taki wielgachny pop-up mam co jakieś 2 tygodnie od Google i jak go sobie jakkolwiek dotnę to mi potem nie ładuje więcej niż jednego ekranu zdjęć, jakiś skrypt się blokuje bez zgody dla Google.

A kod tak zrozumiały jak reklamowy WP.

**Comment by hawkeye116477** [comment]
Jak rzadko się pojawia, to może lepiej to sobie darować.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/49756666-c2f8c500-fcba-11e8-98ad-e1c1a6145019.png)

Wskoczyło na drugi dzień od instalacji Chrome.

**Comment by krystian3w** [comment]
A widzę wadę w pieczeniu ciastka na Google, trzeba by na dwóch domenach np. `google.pl|google.com`, bo jakoś mają bardziej skomplikowany mechanizm weryfikacji że zaakceptowaliśmy politykę.

**Comment by krystian3w** [comment]
Ludzie narzekają, że pop-up RODO/Ciasteczkowy stopuje wideła. Nie działają na to pomysły z `:remove()` a działały niedawno nawet jako `.user.js` w violentmonkey.

Nie są chętni by go zaakceptować lub jak radzi Google logować się na "fejkowe" konto.

uAssets raczej nie wymyśli żadnego `aopr` / `acis` / `aeld` / `set` / `nosiif` / `nostif` by go usuwać szybciej od wadliwego `:remove()` (skoro już nie pomaga).

Pieczenie ciastek nie przejdzie, bo dodatek wykrywa, że ciasteczko istnieje - czyli nie można podwędzić pomysłu z AdGuard aż nie zrobimy więcej sprawdzań czy ciastko ma właściwe wartości poza faktem istnienia.

Klikanie też nie działa z jakiegoś powodu w ramkach, pewnie trzeba by inteligentniej wykrywać "URL". Czasem też się może trafić starsza wersja, gdzie klików trzeba zrobić z przynajmniej 5 (`x1` "dalej" - `x3-4` w strzałkę - "x1 akceptuj").

**Comment by hawkeye116477** [comment]
@krystian3w Podaj jakaś listę kroków co trzeba wykonać, bo nie wiem jak to wywołać.

**Comment by krystian3w** [comment]
Wejdź anonimowo w np. to:

`https://www.youtube.com/watch?v=eVaQ-jQJ19s`

- powinno przywitać cię RODO Google,
- pod RODO np. "zalogowani mają się lepiej" (https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2471)
- oba słyną z stopowania wideo po 1-6 sekundach
- czasem też podmieniany jest player na coś w stylu pop-upa "zalogowani mają się lepiej" (https://github.com/uBlockOrigin/uAssets/issues/7842)

**Comment by krystian3w** [comment]
Google wymyśliło nowy cookie wall dla:

`youtube.com` -> `consent.yotube.com/...`
`news.google.com` -> `consent.google.com/...`
`google.com/maps` -> `consent.google.com/...`

Niby można spróbować dodać klikanie jak cookie wall w sub-domenie jest klikalny (niby powinno się dać lepiej niż z klikaniem w Polymerze).

**Comment by krystian3w** [comment]
Google wycofało się z paywalla, wrócił pop-up "polymer" bez iframe ale nieosiągalny dla:

`youtube.com##+js(clickComplete, [aria-label*="cookie"] > #text, 200, zgadzam)`

lub nie umiem w ten niezbędny xpath lub przebiegów musi być więcej niż 200...

**Comment by krystian3w** [comment]
Google wycofało się z cookie walla na YT, wrócił pop-up "polymer" bez iframe ale nieosiągalny dla:

`youtube.com##+js(clickComplete, [aria-label*="cookie"] > #text, 200, Zgadzam)`

lub nie umiem w ten niezbędny xpath lub przebiegów musi być więcej niż 200...

**Comment by krystian3w** [comment]
Solucja dla `sourceforge.net` by AdGuard Annoyances

```
!##+js(no-setTimeout-if, window.cmpmngr.loadSettings, 30)
sourceforge.net##+js(set-constant, window.cmpmngr.setConsentViaBtn, noopFunc)
```
