### ISSUE TITLE
zgody.infor.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#21]
`https://zgody.infor.pl/?backTo=https://forum.infor.pl/`

Cookie wall na wejście w wątki z Google.

**Comment by hawkeye116477** [comment]
Może :cookie: `inforCookieWallCacheVal` na `15`?

**Comment by krystian3w** [comment]
Jak nagle cię wpuszcza wtedy z linka na forum to może być, sprawdzę jaką liczbę mi wylosują.

**Comment by hawkeye116477** [comment]
@krystian3w Wydaje mi się, że oni raczej nie losują, to raczej stała wartość, zawsze jest 15, nawet w kodzie jest zapisane `https://forum.infor.pl/?icwcv=15`.

**Comment by krystian3w** [comment]
@hawkeye116477  a da się u nas ciastko dla domeny z kropką "`.infor.pl`" niby na takie też się ich skrypt nabiera.

Niby pingwin się z tym męczył by ciasteczka tego typu tworzyć.

**Comment by hawkeye116477** [comment]
@krystian3w Oczywiście, że sią da.

**Comment by krystian3w** [comment]
`https://sklep.infor.pl/landing/infor-akademia/2019/20190830_ewidencja_czasu_pracy/`

**Comment by hawkeye116477** [comment]
@krystian3w To ustaw globalnie na infor.
