### ISSUE TITLE
Google nie ma nic przeciwko

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#22]
> https://chrome.google.com/webstore/detail/polish-cookie-consent/bniijddcmabghibaojbkbnngbedopbno?hl=pl

Trzeba by nauczyć skrypt, by nie wklejał do `manifest.json` informacji:

https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/64d45e7632a70e3d494efce8d44d235ed92aa772/src/manifest.json#L23-L26

I czy da się pod dodatek podpiąć inną osobę lub co potrzeba do nowego skryptu wysyłającego automatycznie dodatek.

**Comment by hawkeye116477** [comment]
@krystian3w Nie testowałem czy to coś będzie działać, ale masz tutaj opisane, co potrzeba => `https://github.com/LinusU/wext-shipit#chrome`. Tutaj chyba możesz dopisać => `https://circleci.com/gh/PolishFiltersTeam/PolishCookieConsent/edit#env-vars`, a jak nie to na maila czy coś :smile:

**Comment by krystian3w** [comment]
A to na pewno nie pod grupę testerów link?

**Comment by hawkeye116477** [comment]
@krystian3w A przeczytałeś uważnie :smile:? Pisze, że jak nie ma Client Secret, to musisz zrobić nowy ID i Secret, a refresh token opisany jest dalej, trzeba z curlem pobawić się.

**Comment by krystian3w** [comment]
`https://circleci.com/gh/PolishFiltersTeam/PolishCookieConsent/edit?#env-vars`

Możesz sprawdzić czy nie wkradły się przed zmienne spacje, ja mogę tylko usuwać.

**Comment by hawkeye116477** [comment]
@krystian3w No właśnie nie mogę, można tylko usuwać :smile:

**Comment by krystian3w** [comment]
OK, to lepiej wstawie 3 raz, marny ten skrypt pod przyciskiem "kopiuj".

**Comment by krystian3w** [comment]
` "refresh_token": "...",`

I jako zmienną tylko to gdzie podmieniłem na kropki?

**Comment by hawkeye116477** [comment]
@krystian3w Tak

**Comment by krystian3w** [comment]
A dodatek zostawić jako niepubliczny, że tylko z linka czy otwieramy się na wyszukiwarkę sklepu Moz://a (tu nie wiem co blokuje) i Google (tu mogę zrobić nawet niby dodatek dla testerów i nikt inny nie zainstaluje nawet - coś jak w Mozilla z dystrybucją poza sklepem tyle że brak jakiś takich mechanizmów ograniczających).

**Comment by hawkeye116477** [comment]
@krystian3w Rozszerzenie jest publiczne w sklepie Moz://i, trzeba wpisać po angielsku, jak wpisze się polską nazwę to o dziwo nie znajduje. Także zrób publiczne w Google, po co ukrywać, raczej ci co mają te strony internetowe to cieszą, się że akceptujemy  :smile:

**Comment by krystian3w** [comment]
OK.

**Comment by krystian3w** [comment]
Niby znów będą go sprawdzać i proponują pod domeny uprawnienia, że do ciastek / localstorage / wszystkiego na domenie.

Więc pewnie w wyszukiwarce wskoczy pewnie w okolicach najwcześniej piątku?

**Comment by hawkeye116477** [comment]
ActiveTab raczej odpada, nie zadziała w przypadku content scripts, a żeby wypisywać konkretne strony to już chyba wcale odpada, tyle tego mamy...

**Comment by krystian3w** [comment]
Jedno dobre, że nie tłumaczą tego na mongolski przez 2 miesiące a w tydzień umieją jakoś zweryfikować, nawet jak robią to już tam tylko boty.

**Comment by hawkeye116477** [comment]
Uprawnienia do Ciastek/Local Storage też raczej są do background scripts, a my korzystamy z content scripts :smile:.

**Comment by krystian3w** [comment]
No to będą musieli przeboleć.

**Comment by hawkeye116477** [comment]
uBO też ma do wszystkiego, w jakieś tam activeTabs się nie bawią, a Nano nie używa tych uprawnień do Ciastek/Local Storage :smile:

**Comment by krystian3w** [comment]
Jeszcze się zobaczy co znowu wypluje API przy kolejnej wersji jak będzie potrzeba.
