### ISSUE TITLE
Opcja ukrycia ikony w Operze / Firefox

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#3]
Skoro na razie nie ma opcji dezaktywacji innej niż z menadżera rozszerzeń, to może dałoby się dopisać opcje ukrywania ikony / "nazwy dodatku" (Firefox mobile / Opera PC / Firefox PC).

Niestety nie wiem gdzie tego szukać w spisach "web addon developerskich", by nie podkradać od konkurencji rozwiązań (jak zrobili własne, bo opisów brak).

**Comment by hawkeye116477** [comment]
@krystian3w Najpierw to może przydałoby się stworzyć jakąś ikonę. Jeśli potrafisz, to zrób ikonę, a ja się zajmę tą opcją ukrywania :smile:.

**Comment by krystian3w** [comment]
Raczej sam ładnej nie zaprojektuje :walking_man:.

**Comment by hawkeye116477** [comment]
@krystian3w 
A co ty na to? ![icon128](https://user-images.githubusercontent.com/19818572/48721483-4ece8280-ec22-11e8-9c7f-bbedddb4e91a.png)

**Comment by krystian3w** [comment]
A da radę bez ucięcia na dole?

**Comment by hawkeye116477** [comment]
@krystian3w Poprawiona wersja, bez ucięcia na dole i ciut jaśniejszy kolor
![icon128_](https://user-images.githubusercontent.com/19818572/48729726-9233eb80-ec38-11e8-8525-33e3514949b8.png)
