### ISSUE TITLE
onlinelifetv.com

### ISSUE THREAD

**Issue by lenkabs** [PolishFiltersTeam/PolishCookieConsent#31]
`1.onlinelifetv.com/21329-house-of-the-witch-2017.html`

**Comment by krystian3w** [comment]
Brak polskiego na stronie, no chyba że robimy z tego międzynarodową ochronę dla całego świata?

**Comment by hawkeye116477** [comment]
Raczej nie.
@lenkabs My nie zajmujemy się ruskimi stronami, takie rzeczy to do zespołu AdGuarda.
