### ISSUE TITLE
rp.pl & parkiet.com

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#32]
<details><summary> old solution </summary>

```
rp.pl#%#(function(){var a=new Date,b=a.getTime();document.cookie="__rppl_rodo_agrmnt=%7B%22u%22%3A%22%22%2C%22t%22%3A"+b+"%2C%22c%22%3A%221%22%7D;domain=.rp.pl;path=/;";})();
```

myślę, że to może być lepsze od aktualizacji jej co jakiś czas jak nagle znowu ktoś zgłosi, że nie działa.

---

```js
(function() {
    var a = new Date,
        b = a.getTime();
    document.cookie = "__rppl_rodo_agrmnt=%7B%22u%22%3A%22%22%2C%22t%22%3A" + b + "%2C%22c%22%3A%221%22%7D;domain=.rp.pl;path=/;";
})();
```

</details>

---

new solution:  https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/c9b6f37a7bba99addfba5b3a6a732e2e8e933f55 https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/c9b6f37a7bba99addfba5b3a6a732e2e8e933f55/src/PCB.txt#L36

**Comment by hawkeye116477** [comment]
A po co tak kombinowałeś? Można było to w jednej linii zrobić i krócej => `Date.now()` :stuck_out_tongue:

**Comment by krystian3w** [comment]
Wygodniej było mi przekopiować na rzywca i użyć  czegoś czytelniejszego niż zmienne a/b.

**Comment by krystian3w** [comment]
@hawkeye116477  a może bot co podbijać będzie Timestamp (np. jak ja tylko dodam filtr a on podbije numer wersji i przy okazji Timestampy).

Niby timestamp z `00000` mamy też w:

https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/15949df9f17981d28f62852245beeb1ef0053a38/src/PCB.txt#L25

Albo nauczyć bakeCookie by sam generował, jak się nie obrazi `Moz://a` i `Opera`.

**Comment by hawkeye116477** [comment]
@krystian3w W przypadku wundergound ta wartość jest stała, oni tego nie zmieniają.

**Comment by hawkeye116477** [comment]
@kiboke Hidden videos on `rp.pl` and `parkiet.com`
Example:
`https://www.rp.pl/Media-i-internet/311079936-Wlasciciele-Multimediow-wycofali-sie-z-transakcji-z-Vectra.html`

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15501 - @hawkeye116477 zamyka ci, mnie chyba się profil Firefox popsuł i nie łapie.

**Comment by hawkeye116477** [comment]
@krystian3w Tak

**Comment by hawkeye116477** [comment]
@krystian3w Sprawdzałem na Waterfoksie, na lisie najwyraźniej jest problem i chyba chodzi o `https://ckon.wordpress.com/2008/07/25/stop-using-windowonload-in-javascript/`.

**Comment by krystian3w** [comment]
Przebudowali pop-up, teraz 2 kliknięcia po sobie:

- dalej,
- zapisz i zamknij,

Niby buttona zapisz obecne polecenie nie widzi, jakby pop-up miał inne ID lub button niedostępny przed kliknięciem `dalej`.

---

Pomysł z cookies zostaje:


**`__gm_rodo_agrmnt:`**`%7B%22t%22%3A1599929898773%2C%22c%22%3A%221%22%7D`
**`__gm_tcfconsent:`**`CO5oe2sO5oe2sBFADAENAyCsAP_AAH_AAB5YGStV_T9fb2vj-_599_t0eY1f9_63t-wzhheMs-8NyZ-X_J4Wv2MyvB34JqQKGRgkunLBAQdtHGncTQgBwIlViTLMYk2MjzNKJrJEmlsbO2dYGH9Pn8XT_ZKZ70-vv__7v3___33_4GStV_T9fb2vj-_599_t0eY1f9_63t-wzhheMs-8NyZ-X_J4Wv2MyvB34JqQKGRgkunLBAQdtHGncTQgBwIlViTLMYk2MjzNKJrJEmlsbO2dYGH9Pn8XT_ZKZ70-vv__7v3___33_4AA.YAAAAAAAAAAA`

do ulepszenia klikaczy, zmiany obecnego klikacza.

**Comment by hawkeye116477** [comment]
Chyba zapomniał powiedzieć, że tym razem sprawa dotyczy jedynie parkietu.

**Comment by krystian3w** [comment]
Nie - na: https://cyfrowa.rp.pl/technologie/51805-ai-przewiduje-kto-popelni-przestepstwo-burza-w-ameryce

Jest już nowsza wersja, chyba że podejmiesz się sprawdzania cyfrowej rp i regionalnych czy mają osadzone wideła.

**Comment by hawkeye116477** [comment]
Patrzyłem na główną rp jedynie.

**Comment by hawkeye116477** [comment]
@krystian3w I co, nie było chyba takie trudne. Dwa razy szybko klika i chyba jest ok.

**Comment by krystian3w** [comment]
Tak, widać spacja za nawiasem też dezaktywuje filtr?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, jest sprawdzana nazwa funkcji bez wycinania żadnych białych znaków. W sumie można to ulepszyć.

**Comment by krystian3w** [comment]
W sumie wygląda jakby porzucili player `x-link.pl` / `x-news.pl` - `onnetwork.tv` ładuje się pomimo pop-upa.

Ale nie wiem czy to nie będzie jak z Interią, że co jakiś czas inny player.

Dodatkowo, w chowany pop-up nie wychodzi praktycznie nigdy klikanie, więc trzeba sięgać po eksperymenty:

```css
rp.pl,parkiet.com##body:not(:has(iframe[src*="x-link.pl/"], iframe[src*="x-news.pl"])) #rodo-popup > div:style(position: absolute !important; left: -9999px !important; top: -1000px !important;)
rp.pl,parkiet.com##body:not(:has(iframe[src*="x-link.pl/"], iframe[src*="x-news.pl"])) #rodo-popup > div > div:style(position: absolute !important; left: -9999px !important; top: -1000px !important;)
```
