### ISSUE TITLE
video.vice.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishCookieConsent#33]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Google Chrome 78
### Dodatkowe informacje mogące mieć znaczenie
`https://video.vice.com/pl/video/bangladeshi-gang-rape/55b7a39ad793cd2d56b40d53`

https://github.com/easylist/easylist/issues/4230

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
```
[{
	"Host raw": "http://.vice.com/",
	"Name raw": "_vice_modal_window_viewed",
	"Path raw": "/",
	"Content raw": "true",
	"Expires": "09-12-2019 16:43:42",
	"Expires raw": "1575906222",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-container-3",
	"First Party Domain": ""
}]
```

```
[{
	"Host raw": "http://.vice.com/",
	"Name raw": "_vice_cmp_modal_viewed",
	"Path raw": "/",
	"Content raw": "true",
	"Expires": "09-12-2019 16:43:42",
	"Expires raw": "1575906222",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-container-3",
	"First Party Domain": ""
}]
```

**Comment by krystian3w** [comment]
@jspenguin2017 / @kiboke / @DandelionSprout (https://github.com/NanoAdblocker/NanoFilters/pull/331)

**Comment by jspenguin2017** [comment]
@krystian3w Cookie notice? Can't reproduce.

**Comment by krystian3w** [comment]
For Germany 🇩🇪  and Poland 🇵🇱 video player is not loaded without this one cookie.

**Comment by krystian3w** [comment]
And cookie pop-up may blocked by many EasyPrivacy filters (`AdGuard AntiTracking Protection` no break pop-up).

**Comment by jspenguin2017** [comment]
https://github.com/NanoMeow/QuickReports/issues/2255
