### ISSUE TITLE
[lite] mapy.geoportal.gov.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/PolishCookieConsent#38]
Na chrome /  firefox:

`https://mapy.geoportal.gov.pl/iMapLite/KMZBPublic.html`

![20191214-1576341138-001](https://user-images.githubusercontent.com/9846948/70851629-b09a0400-1e97-11ea-8a10-11f0a2bd325a.png) |
--- |

**Comment by krystian3w** [comment]
`regulationsAccepted:true`
`rules:1`

@hawkeye116477 pieczenie 2 ciastek, klikadło raczej nie, bo button po przewijaniu się pojawia, może nawet nie istnieje bez przewijania.

**Comment by krystian3w** [comment]
Zacznie działać jak  Google zweryfikuje pozytywnie dodatek w wersji `1.42.1`+ (i potem w nim aktualizacja bazy).

**Comment by hawkeye116477** [comment]
No chyba, że @FadeMind ma Operę, to w takim wypadku musi przejść na Operę Next lub wersję deweloperską albo zaczekać jeszcze tak gdzieś z pół roku :smile:.

**Comment by krystian3w** [comment]
Jak coś to pop-up o nowej kategorii nie może być wycięty - zablokują się inne pop-upy w technologi `angular`.

**Comment by FadeMind** [comment]
@hawkeye116477  @krystian3w  zamiennie Firefox i Chrome. Obecnie Chrome.

**Comment by hawkeye116477** [comment]
@FadeMind W takim razie, może za tydzień będzie nowa wersja, o ile znowu ten ich bot nie zgłupieje i nie odrzuci nam jak ostatnio.

**Comment by hawkeye116477** [comment]
To ja myślałem, że pewnie update dla Chromium będzie po świętach, a tu niespodzianka, wujaszek Google wrzucił dzisiaj update :smile: A w Operze nadal jest w betcie i nie ma komu zrecenzować.

@FadeMind Jakbyś miał się kiedyś przesiąść na Whale Browser, to pewnie musiałbyś sporo czekać na update, bo @krystian3w narozrabiał i dali mu :banana: , ale powiedzieli, że zdejmą, jak przyjedzie do Korei do ich siedziby, uklęknie przed Prezesem i przeprosi :smile:

**Comment by krystian3w** [comment]
Albo napisali a mail się zgubił, trzeba było użyć Gmaila do rejestracji a nie głupiej Interii.
