### ISSUE TITLE
Promise resolved while context is inactive [whitelist button]

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#45]
### "🔺"⚠️ Promise resolved while context is inactive

```
index.js:24
    <anonimowa> moz-extension://8c3b6ef0-53a9-47a7-939d-d48dc8c0183d/popup/index.js:24
```
```
index.js:36
    <anonimowa> moz-extension://8c3b6ef0-53a9-47a7-939d-d48dc8c0183d/popup/index.js:36
```
```
index.js:49
    <anonimowa> moz-extension://8c3b6ef0-53a9-47a7-939d-d48dc8c0183d/popup/index.js:49
```

https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/0303da9fcfdc15aa9d212703ddcde95213544d97/src/popup/index.js#L24

---

<table><tr><td>
Gecko/Servo  <td>Firefox 71
<tr><td>Wersja <td> 1.42.1 (AMO)
</table>

**Comment by krystian3w** [comment]
I czy od nowej instalacji musi minąć 7 dni? Od ostatniej aktualizacji listy minęły z 2 tygodnie.

Opcjonalnie mam uszkodzony Windows / Firefox.

**Comment by hawkeye116477** [comment]
@krystian3w Tak, od nowej instalacji musi minąć 7 dni.
A ten „błąd" to kiedy i gdzie się pojawia? Niestety nie mam szklanej kuli...

**Comment by krystian3w** [comment]
No próbuję dodać np. `youtube` do białej listy przyciskiem i się nie odświeża na "włącz", taki jakby loop - w panelu sterowania też brak na białej liście `youtube.com`.

Sprawdzałem też czy może biała lista tylko dla domen z listy filtrów - też loop jak próbuję dać wyłącz z pop-upa na np. #38.

"Error" wyciągnięty z konsoli javascript przeglądarki (nie devtools spod F12).

**Comment by hawkeye116477** [comment]
@krystian3w https://github.com/PolishFiltersTeam/PolishCookieConsent/commit/809ec786758209de60492f45a222600821714c4b

**Comment by krystian3w** [comment]
Tak wtedy po debugowaniu nowszego kodu przycisk działa OK, domena pojawia się w panelu sterowania.

**Comment by krystian3w** [comment]
Zapomniałem uaktualnić `manifest.json`. 🥇

**Comment by hawkeye116477** [comment]
Nic nie szkodzi i tak miałem jeszcze dodać jedną poprawkę :smile:

**Comment by krystian3w** [comment]
Próbujesz robić jak uBO, że wykrywa że lista ma więcej niż 7 dni a na github nowsza?

**Comment by hawkeye116477** [comment]
Nie

**Comment by krystian3w** [comment]
A draft można robić na WWW czy to magia Git-krakena?

**Comment by hawkeye116477** [comment]
@krystian3w Do CWS musisz ręcznie wysłać, bo coś nie idzie.

**Comment by hawkeye116477** [comment]
Nie robiłem drafta, usuwałem stary tag przez GK...

**Comment by krystian3w** [comment]
A czyli w chwili usuwania  `releases` zielone zmienia się w czerwony `draft`.

**Comment by hawkeye116477** [comment]
@krystian3w Tak
