### ISSUE TITLE
dodatek do firefoxa zgoda ciasteczkowa nie działa na stronie interia.pl 

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishCookieConsent#53]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 76.01
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Tak samo https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/54#issuecomment-633053665
