### ISSUE TITLE
nczas.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishCookieConsent#56]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 77.01
### Dodatkowe informacje mogące mieć znaczenie
Polska zgoda ciasteczkowa nie blokuje strony nczas.com 

Dodatkowo sprawdziłem te wasze filtry o nazwie "`I don't care about cookies`" i dalej strony grupy wp.pl nie są z nimi blokowane. 

Jedynie zgoda ciasteczkowa działa na strony całej grupy wp.pl ale z lekkim lagiem. Jak nie urok to ~~sraczka~~ ...

Dużo ludzi posiada słabe lub średnie komputery a instalowanie 5 tys. rozszerzeń na nich mija się z celem ...

Prośba do was aby w końcu zrobić z tym porządek 

W tej linii jest blokada popup **Newslettera** do poczty `wp.pl` i chyba do samej strony `wp.pl` i na poczcie wp.pl nie wyskakuje nic ...
```
~poczta.wp.pl,wp.pl,~www.wp.pl#?#tr[data-reactid]:not([class]):not([id]) > td[class] > div[class*=" "]:-abp-has( > div > iframe[id^="fm"][src*="freshmail.io"])
```

Posiadane filtry do blokowania RODO 
* Polskie Filtry Elementów Irytujących (zawierają RODO)
* I don't care about cookies 
* Inne filtry standardowe EasyList  i EasyPrivacy

albo zamiast tych 2 filtrów stosuję te od AdGuarda `AdGuard Base` i `AdGuard Annoyances`

Wydaje mi się że problem leży po stronie jakieś głównej reguły blokującej RODO w jednym z podstawowych filtrów w ublocku bo w dodatku AdGuarda do Firefoxa (dokładnie te same filtry co w uB)) nie ma tych problemów i strony z grupy wp.pl są dobrze blokowane na RODO ...

3 godziny na to straciłem ... to może jakiś programista w końcu to poprawi u was do uBO?

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
> Polska zgoda ciasteczkowa nie blokuje strony nczas.com

To nie jest błąd, od tego jest lista I don't care about cookies, jak już wcześniej komuś też pisałem => https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2048#issuecomment-641959021. Jeżeli lista jest zaznaczona i nadal nie trybi, to należy wyczyścić cache i ciasteczka lub `ctrl+F5` 

> Dużo ludzi posiada słabe lub średnie komputery a instalowanie 5 tys. rozszerzeń na nich mija się z celem ....

No bez przesady, taka Polska Ciasteczkowa Zgoda raczej zbytnio większego obciążenia nie generuje. Niestety uBO ma ograniczenia, dostępu do wszystkiego nie chcą dodać, więc konieczne jest osobne rozszerzenie...

> Wydaje mi się że problem leży po stronie jakieś głównej reguły blokującej RODO w jednym z podstawowych filtrów w ublocku bo w dodatku Adguarda do Firefoxa (dokładnie te same filtry co w Ublocku) nie ma tych problemów i strony z grupy wp.pl są dobrze blokowane na RODO ...

Działa to jedynie na Firefoksie i uBO takiego czegoś nie ma.

**Comment by krystian3w** [comment]
> A to już pretensje do gorhilla albo raczej grupy WP

Nikt mu nie broni dodać `replace` szybciej w Nano Adblocker jak ma już gotowy kod i się wstydzi jego jakości/czytelności lub przekonać gorhilla by dodać je do uBO (jako uzupełnienie mocy dla Firefox).

Problem że chrome już raczej nie zapewni wsparcia a aplikacja Nano Adblocker na Windows dalej nie istnieje..., pewnie ten brak wsparcia na chrome hamuje dodanie.

---

`replace` w polskich listach nie zadziała, bo nie dostaniemy w AdGuard uprawnień `full` - raczej nikt nie będzie ręcznie subskrybował jak może włączyć `AdGuard Annoyance` - poza tym raczej my jeszcze nie ogarniamy jak tego używać jak filtr padnie lub będzie się dziwnie zachowywać w aplikacji na Windows / macOS / Android (już takie bugi były i na szybko dezaktywowano filtr).

---

Liczby filtrów też się pewnie nie da łatwo zmniejszyć jak przymulają 15 letnie PC.

**Comment by krystian3w** [comment]
Dodatkowo cytowany FreshMail to tylko pop-up newsletter, żadne tam rodo.

--

Pewnie we wrześniu go WP wycofa jak zachorowanie SARS-COV-2 spadnie drastycznie i nagle znikną limity na sklepy / autobusy.
