### ISSUE TITLE
vibez.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishCookieConsent#60]
Nowy serwis WP
![Zrzut ekranu z 2020-10-04 03-45-15](https://user-images.githubusercontent.com/36385327/95005095-08a32200-05f4-11eb-9065-822acb9cba48.png)

**Comment by xMaap** [comment]
rodobox.io można chyba usunąć bo nie działa.

**Comment by krystian3w** [comment]
znaczy koniec `rodobox` czy 3 strony padły?

**Comment by hawkeye116477** [comment]
Koniec Rodobox.

**Comment by krystian3w** [comment]
A te 3 strony już wymieniły czy dalej mają error 404 w konsolach?

**Comment by hawkeye116477** [comment]
Totalna reklama ma komunikat o ciastkach i niedziałające linki do polityki w stopce. Selectshop ma zwykły zamykamy komunikat.
