### ISSUE TITLE
mapaodoru.pgkslupsk.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#64]
![obraz](https://user-images.githubusercontent.com/35370833/101377783-93cdbc00-38b2-11eb-84f4-2cf89e0ebb6c.png) |
--- |

https://github.com/MajkiIT/polish-ads-filter/issues/18064 - wycięcie listy z polami wyboru blokuje dodanie wpisu.

Akceptacja tam raczej pociąga za sobą akceptowanie takich rzeczy w newsletterach / formularzach rejestracji?

Dodatkowo strona chyba nie chce obsługiwać:

`mapaodoru.pgkslupsk.pl(clickInteractive, #wpgmza_ugm_spm)`
`mapaodoru.pgkslupsk.pl(clickTimeout, #wpgmza_ugm_spm)`

---

Jak się nie zaznaczy to niby wychodzi, że używają tego jako reCaptcha: 

> Udowodnij, że jesteś człowiekiem, zaznaczając opcję powyżej

Wtedy nagle dodatek musiałby awansować do miana walki z systemami przeciwko ludziom?

**Comment by krystian3w** [comment]
taki Vanila JS umie zaznaczyć:

```js
document.getElementById("wpgmza_ugm_spm").click();
```

**Comment by krystian3w** [comment]
Niby rusza takie:

`mapaodoru.pgkslupsk.pl(clickComplete, input#wpgmza_ugm_spm, jestem_czlowiekiem)`

**Comment by hawkeye116477** [comment]
Raczej odrzucamy. Wpisuje się dane, więc normalne, że trzeba zaznaczyć, by wyrazić zgodę, tak jak przy rejestracji. Więc tak jak mówisz, skoro to akceptujemy, to i przy rejestracji albo newsletterze też powinniśmy...
