### ISSUE TITLE
Baza filtrów cofa czasem się do wbudowanej w ostatnią wersje

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishCookieConsent#72]
Sam mam to co jakiś czas, najczęściej zbiega się z aktualizacją Firefox.

Komentarz w Chrome Web Store może wskazuje, że "użytkowniczka" też to miała np. bo śledzi co zostało dodane po czerwcu 2020.

**Comment by hawkeye116477** [comment]
Ta, najwyraźniej problem jest tu => https://github.com/PolishFiltersTeam/PolishCookieConsent/blob/master/src/update.js#L18.


Trzeba będzie doprecyzować => https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason.

**Comment by krystian3w** [comment]
A takie coś pozwoli na prace w ramkach?

```diff
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "js": [
        "content.js"
      ],
+++   "all_frames": true,
      "run_at": "document_start"
    }
  ],
```

Niby raz na rok się zdarza pop-up używający iframe, w takich żadne klikanie nie działało i trzeba było polegać na czytelności cookies/localStorage.

Chyba, że bezpieczniej dodawać nieczytelne dla ludzi wpisy w cookies/localStorage.

**Comment by hawkeye116477** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts
 > Note: This also applies to any tracker or ad that uses iframes, which means that enabling this could make your content script get called dozens of times on some pages.

**Comment by krystian3w** [comment]
A naprawiamy bug z zwklejaniem np. `||` do listy wyjątków lub konwersji pustych linii w `|||` np.:

```
abc.pl


def.pl
```

działa jak `abc.pl|||def.pl`
